<?php

declare(strict_types=1);

namespace Survos\DepotBundle\Command;

use Survos\DepotBundle\Protocol\DepotProtocol;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

/**
 * Writes the constants ai-tools needs, from depot rather than from ssai.
 *
 * ai-tools and depot are always on the same machine; ssai is somewhere else
 * entirely, and on an appliance it is not installed at all. Generating this file
 * from ssai meant the edge either carried a checkout it should not have, or --
 * worse, and this is what happened -- carried a broken one: app:dump-constants
 * died on a missing vendor/, the file stayed empty, and ai-tools came up
 * healthy-looking and blind. Nothing crops, every signal green.
 *
 * The shared dir is reported, not invented. If it is not declared in the
 * environment this command fails, because a guessed storage path is precisely
 * the failure being fixed.
 */
#[AsCommand('depot:dump-constants', 'Write constants_local.py for the co-located ai-tools process')]
final class DumpConstantsCommand
{
    public function __construct(
        #[Autowire('%env(default::AI_TOOLS_SHARED_DIR)%')]
        private readonly ?string $sharedDir,
        #[Autowire('%kernel.project_dir%')]
        private readonly string $projectDir,
    ) {
    }

    public function __invoke(
        SymfonyStyle $io,
        #[Option('Where to write the Python constants', name: 'py-output')]
        string $pyOutput = '../ai-tools/constants_local.py',
    ): int {
        $sharedDir = trim((string) $this->sharedDir);

        if ($sharedDir === '') {
            $io->error(sprintf(
                '%s is not set. Declare the storage root in the environment (systemd: '
                . 'Environment=%s=/path/to/storage) -- it is a property of this machine, '
                . 'not something this command should guess.',
                DepotProtocol::SHARED_DIR_ENV,
                DepotProtocol::SHARED_DIR_ENV,
            ));

            return Command::FAILURE;
        }

        if (!is_dir($sharedDir)) {
            // Warn rather than fail: on a station whose storage is an external
            // drive, the mount may simply not be up yet, and the caller can
            // reasonably retry. Silence would be the wrong answer either way.
            $io->warning(sprintf('Shared dir does not exist (yet): %s', $sharedDir));
        }

        $path = str_starts_with($pyOutput, '/') ? $pyOutput : $this->projectDir . '/' . $pyOutput;
        $dir = \dirname($path);

        if (!is_dir($dir)) {
            $io->error(sprintf('Output directory does not exist: %s', $dir));

            return Command::FAILURE;
        }

        $lines = [
            '# AUTO-GENERATED. DO NOT EDIT.',
            '# Written by depot: bin/console depot:dump-constants',
            '#',
            '# Generated by depot, not ssai: depot is the process that shares a machine',
            '# with ai-tools, so it is the one that can speak for this station.',
            '',
            'PROTOCOL_VERSION = ' . DepotProtocol::VERSION,
            '',
            '# Storage root for this station, as declared in its environment.',
            'AI_TOOLS_SHARED_DIR = ' . json_encode($sharedDir),
            '',
        ];

        file_put_contents($path, implode("\n", $lines));

        $io->success(sprintf('Wrote %s (protocol v%d, shared dir %s)', $path, DepotProtocol::VERSION, $sharedDir));

        return Command::SUCCESS;
    }
}
